import Head from 'next/head'
import styles from '../styles/MainLayout.module.css'
import { getLatestUpdates, getMenu, getPageById, getPageBySlug, getSlideshow } from '../contentful'
import { Menu } from '../components/Menu'
import { Slideshow } from '../components/Slideshow'
import { Footer } from '../components/Footer'
import { UpdateText } from '../components/UpdateText'
import { PageText } from '../components/PageText'
import { Submenu } from '../components/Submenu'
import { Search } from '../components/Search'
export default function Home({ 
  menu, 
  show = [], 
  slug, 
  page = {}, 
  updates = [],
  neighborhoods 
}) {
  return (<>
      <Head>
        <title>{page && page.seoTitle || 'Arbor Lodge Neighborhood, Portland OR'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <nav>
        <Menu items={menu} />
      </nav>
      <Slideshow images={show} />  
      
      <main className={`${styles.main} ${styles.container}`}>
        <section className={styles.left}>
          {(page && !slug) && // homepage should just map updates
            updates.map(update => <UpdateText key={update.title} {...update} />)
          }
          {page && slug && // found page, display title and content
            <PageText title={page.title} content={page.pageContent} />
          }
          {!page && // not found page, display 404
            <h1>Sorry, there doesn't seem to be anything at this URL.</h1>
          }
        </section>

        <section className={styles.right}>
          <Search />
          {slug ? <Submenu menu={menu} page={page} /> : null}
          <iframe 
            src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11171.697016678798!2d-122.6923388!3d45.5719618!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5495a7a3b74d15c1%3A0xf60b1b34aa1f920b!2sArbor%20Lodge%2C%20Portland%2C%20OR%2097217!5e0!3m2!1sen!2sus!4v1640201179662!5m2!1sen!2sus" 
            width="100%" 
            height="350" 
            style={{ border: 0 }}
            allowfullscreen="" 
            loading="lazy"
          />
          
          <br /><br />
          <PageText title={neighborhoods.title} content={neighborhoods.text} />
        </section>
      </main>

      <Footer items={menu} />
    </>)
}

export const getServerSideProps = async ({ query, res }) => {
  var menu = await getMenu()
  var show = await getSlideshow()
  var updates = await getLatestUpdates()
  var neighborhoods = await getPageById('4ydMQwzKqYOJGLAeZqp9DG')

  // dynamic page created by slug
  var slug = query.slug ? query.slug[0] : null
  var page = slug 
    ? await getPageBySlug(slug)
    : await getPageById('6wKUqAuj95bWl80kpUreYN')

  // 404 if we dont get a page
  if (!page) {
    res.statusCode = 404
  }

  return {
    props: { 
      menu, 
      page: page ? page : null,  // page undef is causing serialization error here.  
      show, 
      updates,
      slug,
      neighborhoods 
    },
  };
}
