import Head from 'next/head'
import styles from '../styles/Text.module.css'
import { getMenu, getPageById, getSlideshow } from '../contentful'
import { Menu } from '../components/Menu'
import { Slideshow } from '../components/Slideshow'

export default function Home({ menu, show = [], page = {} }) {
  return (
    <div className="container">
      <Head>
        <title>{page.seoTitle || 'Arbor Lodge Neighborhood, Portland OR'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Menu items={menu} />
      </nav>
      

      <main className={styles.main}>
        <Slideshow images={show} />  
        <iframe 
          src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11171.697016678798!2d-122.6923388!3d45.5719618!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5495a7a3b74d15c1%3A0xf60b1b34aa1f920b!2sArbor%20Lodge%2C%20Portland%2C%20OR%2097217!5e0!3m2!1sen!2sus!4v1640201179662!5m2!1sen!2sus" 
          width="100%" 
          height="350" 
          style={{ border: 0 }}
          allowfullscreen="" 
          loading="lazy"
        />

      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export const getServerSideProps = async () => {
  var menu = await getMenu()
  var page = await getPageById('6wKUqAuj95bWl80kpUreYN')
  var show = await getSlideshow()
  return {
    props: { menu, page, show },
  };
}
